server:
  port: 8081
  ssl:
    key-store: src/main/resources/testhttps.keystore
    key-store-type: JKS
    key-alias: testhttps
    enabled: true
    key-store-password: 111111

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10240MB
      max-request-size: 10240MB
logging:
  file:
    name: application.log
    path: log/

hdfs_uri: hdfs://192.168.111.134:9020
hadoop_user_name: root
#hdfsPath: /datapool/az/public/data/az0001
hdfsPath: /test